name: CI

on:
  push:
    branches: 
    - develop
    - main
  pull_request:
    branches:
    - develop
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests with Maven
      run: mvn test
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: antoniocaia/restdemo:latest

#    - name: Build 
#      run: docker build -t rest-demo/backend . -f src/main/docker/backend/Dockerfile
#    - name: Push 
#      run: docker push rest-demo/backend 
 
      
